apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  source:
    path: dev
    repoURL: 'https://github.com/ayushk048-Tandem/kube-configs.git'
    targetRevision: HEAD
  
  destination:
    name: ''
    server: 'https://kubernetes.default.svc'
    namespace: myapp

  project: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
    syncOptions:
      - CreateNamespace=true