apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: argopoc.azurecr.io/logging-demo:1.0.1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: acr-secrets
