apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: webapp
        image: logging-demo:1.0.1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: webapp-configmap
        imagePullPolicy: Never