resources:
- ../../base

# patches:
#   - replicas.yaml

Namespace: dev

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: webapp-deployment
      spec:
        replicas: 1
        template:
          spec:
            containers:
            - name: webapp
              image: logging-demo:1.0.3
  - patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: webapp-service
      spec:
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80
            nodePort: 30102

commonLabels:
  app: dev-webapp

configMapGenerator:
- name: webapp-configmap
  env: config.properties